name: yak_result_example
description: A sample command-line application.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  yak_result: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
