name: yak_result_example
description: A sample command-line application.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  yak_result: ^3.0.1


dev_dependencies:
  lints: ^4.0.0
