name: yak_packages

packages:
  - examples/**
  - packages/**

ignore:
  - packages/**/example

command:
  bootstrap:
    environment:
      sdk: '>=3.3.3 <4.0.0'

scripts:
 test:
    description: Test ALL Applications and Packages
    run: |
      melos exec -c 1 \
      --fail-fast \
      -- \
      melos run test:flutter && \
      melos run test:dart
    packageFilters:
      dirExists: 
        - test

  test:flutter:
    description: Test Flutter Applications and Packages
    run: |
      melos exec -- flutter test
    packageFilters:
      flutter: true
      dirExists: 
        - test

  test:dart:
    description: Test Dart Applications and Packages
    run: |
      melos exec -- dart test
    packageFilters:
      flutter: false
      dirExists: 
        - test