name: yak_flutter_example
description: An example app for yak_flutter package.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  yak_flutter: ^2.0.0

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true