name: stub_example
description: A sample command-line application.
publish_to: 'none'
version: 2.0.0

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  stub: ^2.1.2
  test: ^1.25.8
  
dev_dependencies:
  lints: ^4.0.0

