name: stub
description: a pure `dart` lightweight package to help you stub methods for your tests
version: 2.0.1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  meta: ^1.11.0
  yak_utils: ^2.0.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
