name: adaptive_style
description: a Flutter package for a scalable, adaptive and responsive UI
version: 0.0.5
homepage: https://github.com/yakforward-ou/yak_packages

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  yak_flutter: ^3.0.2
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
