name: adaptive_style
description: Make you Flutter UI both responsive and adaptive
version: 0.0.1
homepage: https://github.com/yakforward-ou/yak_packages

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
