name: otp_server
description: a ready to use server to implement OTP authentication
version: 0.0.1
homepage: https://github.com/yakforward-ou/yak_packages

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  meta: ^1.11.0
  yak_runner: ^3.0.1

dev_dependencies:
  # mocktail: ^1.0.3
  lints: ^3.0.0
  # test: ^1.24.9
  # stub: ^2.1.1
  # yak_test: ^2.0.1