name: yak_utils
description: a collection of useful functions and extensions` for your projects
version: 2.0.1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  meta: ^1.11.0

dev_dependencies:
  mocktail: ^1.0.1
  lints: ^3.0.0
  test: ^1.24.9
  stub: ^2.0.1
  yak_test: ^2.0.1