name: yak_utils
description: a collection of useful functions and extensions` for your projects
version: 2.1.2
homepage: https://github.com/yakforward-ou/yak_packages

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  meta: ^1.15.0

dev_dependencies:
  mocktail: ^1.0.3
  lints: ^4.0.0
  test: ^1.25.8
  stub: ^2.1.2
  yak_test: ^3.0.3