name: yak_runner
description: A Dart package that makes running functions safer and easier to test
version: 3.0.3
homepage: https://github.com/yakforward-ou/yak_packages

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  meta: ^1.15.0
  yak_result: ^3.0.1
  yak_utils: ^2.1.2

dev_dependencies:
  lints: ^4.0.0
  stub: ^2.1.2
  test: ^1.25.8
