name: yak_runner
description: A Dart package that makes running functions safer and easier to test
version: 2.1.1
homepage: https://github.com/yakforward-ou/yak_packages

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  meta: ^1.11.0
  yak_result: ^2.1.1
  yak_utils: ^2.1.1

dev_dependencies:
  lints: ^3.0.0
  stub: ^2.1.1
  test: ^1.24.9
