name: yak_runner
description: A Dart package that makes running functions safer and easier to test
version: 2.0.1
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  meta: ^1.10.0
  yak_result: ^2.0.1
  yak_utils: ^2.0.1

dev_dependencies:
  lints: ^3.0.0
  stub: ^2.0.0
  test: ^1.24.9
