name: 'test'
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    name: 'run flutter_test and analyze'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4 
      - name: 'setup flutter'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: 'update PATH'
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH && \
          echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV         
      - name: 'activate coverage' 
        run: |
          dart pub global activate coverage
      - name: 'setup melos'
        uses: bluefireteam/melos-action@v3
      - name: 'run tests'
        run: |
          melos run test
  # https://josh-ops.com/posts/github-code-coverage/
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md