name: test
on:
  pull_request:
    branches: [main]
jobs:
  test:
    name: run tests and analyze
    runs-on: [ubuntu-latest]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4 
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v3
      - run: |
          melos analyze && \
          melos format && \
          melos run test