name: yak_tween
description: A replica of flutter Tween that allows `const` constructor and accepts/returns only NN.
version: 2.0.4
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  yak_utils: ^2.1.2


dev_dependencies:
  test: ^1.25.8
  flutter_lints: ^4.0.0