name: yak_tween
description: A replica of flutter Tween that allows `const` constructor and accepts/returns only NN.
version: 2.0.3
homepage: https://github.com/iapicca/yak_packages

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  yak_utils: ^2.0.2

dev_dependencies:
  test: ^1.24.9
  flutter_lints: ^3.0.2